### ISSUE TITLE
`TypeElementWrapper.getInnerTypes(…)` only returns classes

### ISSUE THREAD

**Issue by odrotbohm** [toolisticon/aptk#162]
Contrary to what the method name implies, `….getInnerTypes(…)` only returns inner classes. I would expect the method to also return interfaces and records, i.e., everything that is a type in Java.

**Comment by tobiasstamann** [comment]
Hi, sorry for the late response. I will try to fix it asap.

**Comment by tobiasstamann** [comment]
I have created the release 0.29.0 which includes the fix, it will be available in maven central in a couple of hours.
Please contact me, if something else needs to be adjusted/added.
