### ISSUE TITLE
`TypeElementWrapper.getOuterType()` fails for class contained in an interface

### ISSUE THREAD

**Issue by odrotbohm** [toolisticon/aptk#163]
Given the following arrangement:

```java
interface Foo {

  class Bar {}
}
```

, a `TypeElementWrapper` obtained for `Bar` will return an empty `Optional` for the call to `getOuterType()` as that only looks for parent elements of `ElementKind.CLASS`.

**Comment by odrotbohm** [comment]
This has just [come up](https://github.com/spring-projects/spring-modulith/issues/962) again in Spring Moduliths APT in a related way.

**Comment by tobiasstamann** [comment]
Hi Oliver, don't know why but somehow this issue went passed my radar. I will provide a fix later today.

**Comment by tobiasstamann** [comment]
Both issues are fixed now. I will trigger the release later today.

**Comment by odrotbohm** [comment]
Already [upgraded](https://github.com/spring-projects/spring-modulith/issues/993)! 🙇
